prompt:
  colors:
    primary: 65
    secondary: 59
    tertiary: 108
  emoji: üêä
pve_host_index: 17
pve_ip_address: 10.3.0.117
pve_mac_address: de:fe:c8:03:00:75
pve_vm_id: '117'
pve_lxc_template: "local:vztmpl/ubuntu-22.10-standard_22.10-1_amd64.tar.zst"
pve_vm_name: 'ambrose'
pve_swap: 512
pve_memory: 16384

pve_option_unprivileged: true
pve_option_onboot: true
pve_option_start: true
pve_cores: 4
